# Generated by Django 4.2 on 2024-07-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_county_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBigTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSmallTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bigTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itembigtag')),
            ],
        ),
    ]
