# Generated by Django 4.2 on 2024-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_networkgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkgraph',
            name='csv',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
